from matplotlib.colors import LinearSegmentedColormap

RESAMPLING = "cubic"
CONSTRAIN_NEGATIVE_LE = False
CONSTRAIN_PET = False
SUPPLY_SWIN = False
UPSCALE_TO_DAYLIGHT = False
DEFAULT_CONFIGURATION = "ECOv003"
MALLICK2014_CONFIGURATION = "MALLICK2014"
MALLICK2015_CONFIGURATION = "MALLICK2015"
MALLICK2016_CONFIGURATION = "MALLICK2016"

RHO_KGM3 = 1.2  # Air density (kg m-3)
CP_JKG = 1013  # Specific heat of air at constant pressure (J/kg/K)
GAMMA_HPA = 0.67  # Psychrometric constant (hpa/K)
PT_ALPHA = 1.26  # Priestley-Taylor coefficient
SB_SIGMA = 5.67e-8  # Stefann Boltzmann constant
DEFAULT_G_METHOD = "santanello"
LE_CONVERGENCE_TARGET_WM2 = 2.0
ECOv002_LE_CONVERGENCE_TARGET_WM2 = 1.0
MAX_ITERATIONS = 30
ECOv002_MAX_ITERATIONS = 3
ECOv003_G_METHOD = "sebal"
ECOv002_G_METHOD = "santanello"
ECOv003_CONSTRAIN_NEGATIVE_LE = False
ECOv002_CONSTRAIN_NEGATIVE_LE = False
ECOv003_CONSTRAIN_PET = False
ECOv002_CONSTRAIN_PET = True
ECOv003_APPLY_SURFACE_EMISSIVITY_TO_LWIN = False
ECOv002_APPLY_SURFACE_EMISSIVITY_TO_LWIN = True
MALLICK2014_G_METHOD = "sebal"
MALLICK2014_CONSTRAIN_NEGATIVE_LE = False
MALLICK2014_CONSTRAIN_PET = False
MALLICK2014_APPLY_SURFACE_EMISSIVITY_TO_LWIN = False
MALLICK2014_RUN_ITERATIVE_CONVERGENCE = False
MALLICK2014_USE_BUCK_DEWPOINT = True
MALLICK2014_USE_VARIABLE_ALPHA = False
MALLICK2014_CONSTRAIN_LE_TO_AVAILABLE_ENERGY = False
# 2015: moisture-constrained EF, iterative, variable alpha (~25 iterations for flux stability)
MALLICK2015_G_METHOD = "sebal"
MALLICK2015_MAX_ITERATIONS = 25
MALLICK2015_CONSTRAIN_NEGATIVE_LE = False
MALLICK2015_CONSTRAIN_PET = False
MALLICK2015_APPLY_SURFACE_EMISSIVITY_TO_LWIN = False
MALLICK2015_RUN_ITERATIVE_CONVERGENCE = True
MALLICK2015_USE_BUCK_DEWPOINT = True
MALLICK2015_USE_VARIABLE_ALPHA = True
MALLICK2015_CONSTRAIN_LE_TO_AVAILABLE_ENERGY = False
# 2016 uses the same STIC1.2 algorithm as 2015; constants alias accordingly
MALLICK2016_G_METHOD = MALLICK2015_G_METHOD
MALLICK2016_MAX_ITERATIONS = MALLICK2015_MAX_ITERATIONS
MALLICK2016_CONSTRAIN_NEGATIVE_LE = MALLICK2015_CONSTRAIN_NEGATIVE_LE
MALLICK2016_CONSTRAIN_PET = MALLICK2015_CONSTRAIN_PET
MALLICK2016_APPLY_SURFACE_EMISSIVITY_TO_LWIN = MALLICK2015_APPLY_SURFACE_EMISSIVITY_TO_LWIN
MALLICK2016_RUN_ITERATIVE_CONVERGENCE = MALLICK2015_RUN_ITERATIVE_CONVERGENCE
MALLICK2016_USE_BUCK_DEWPOINT = MALLICK2015_USE_BUCK_DEWPOINT
MALLICK2016_USE_VARIABLE_ALPHA = MALLICK2015_USE_VARIABLE_ALPHA
MALLICK2016_CONSTRAIN_LE_TO_AVAILABLE_ENERGY = MALLICK2015_CONSTRAIN_LE_TO_AVAILABLE_ENERGY
USE_VARIABLE_ALPHA = True
SHOW_DISTRIBUTIONS = True

ET_COLORMAP = LinearSegmentedColormap.from_list("ET", [
    "#f6e8c3",
    "#d8b365",
    "#99974a",
    "#53792d",
    "#6bdfd2",
    "#1839c5"
])

GEOS5FP_INPUTS = [
    "Ta_C",
    "RH"
]
